wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1715782022.994
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.10.6
      5: 0.14.0
      8:
      - 5
    visualize:
      my_custom_plot_id:
        panel_config:
          fieldSettings:
            stroke: null
            x: x
            y: y
          panelDefId: wandb/line/v0
          stringSettings:
            title: Custom Y vs X Line Plot
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: my_custom_plot_id_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
